import { Link } from 'react-router-dom'
import { useEffect } from 'react'

export default function Terms() {
  useEffect(() => {
    document.title = 'Terms of Service — ListingIgnite'
    window.scrollTo(0, 0)
  }, [])

  return (
    <div style={s.page}>
      <div style={s.container}>

        <Link to="/" style={s.backLink}>← Back to Home</Link>

        <header style={s.header}>
          <div style={s.sparkle}>✦</div>
          <h1 style={s.pageTitle}>Terms of Service</h1>
          <p style={s.lastUpdated}>Last Updated: April 5, 2026</p>
          <p style={s.disclaimer}>
            Note: These terms were prepared using AI assistance and have not been reviewed by a licensed attorney.
            We recommend consulting legal counsel before scaling to a large user base.
          </p>
        </header>

        <div style={s.body}>

          <Section title="1. Acceptance of Terms">
            <p>By accessing or using ListingIgnite at listingignite.com, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>ListingIgnite is a SaaS platform that uses artificial intelligence to generate marketing content for real estate listings, including MLS descriptions, social media posts, email blasts, flyer copy, video scripts, and SEO landing page copy.</p>
          </Section>

          <Section title="3. Account Registration">
            <ul style={s.list}>
              <li>You must provide accurate information when creating an account</li>
              <li>You are responsible for maintaining the security of your account credentials</li>
              <li>You must be at least 18 years old to use ListingIgnite</li>
              <li>One person or entity may not maintain more than one free account</li>
            </ul>
          </Section>

          <Section title="4. Credits and Payment">
            <ul style={s.list}>
              <li>New accounts receive 3 free credits upon signup</li>
              <li>Each generation of marketing content (all 6 formats) costs 1 credit</li>
              <li>Credits are deducted only upon successful generation and saving of content</li>
              <li>Failed generations due to technical errors are not charged</li>
              <li>Purchased credits are non-refundable unless required by applicable law</li>
              <li>We reserve the right to change credit pricing with reasonable notice</li>
            </ul>
          </Section>

          <Section title="5. Acceptable Use">
            <p>You agree not to:</p>
            <ul style={s.list}>
              <li>Use ListingIgnite for any unlawful purpose</li>
              <li>Submit false, misleading, or fraudulent listing information</li>
              <li>Attempt to reverse engineer, copy, or replicate the service</li>
              <li>Use automated scripts or bots to access the service</li>
              <li>Resell or redistribute generated content as a competing AI service</li>
              <li>Attempt to circumvent the credit system</li>
            </ul>
          </Section>

          <Section title="6. AI-Generated Content">
            <ul style={s.list}>
              <li>Content generated by ListingIgnite is produced by artificial intelligence and may contain errors, inaccuracies, or omissions</li>
              <li>You are solely responsible for reviewing, editing, and verifying all generated content before use</li>
              <li>ListingIgnite makes no guarantees about the accuracy, completeness, or fitness of AI-generated content for any particular purpose</li>
              <li>Generated content should comply with your local MLS rules, fair housing laws, and real estate regulations</li>
              <li>You retain ownership of the content generated using your listing data</li>
            </ul>
          </Section>

          <Section title="7. Intellectual Property">
            <ul style={s.list}>
              <li>ListingIgnite and its original content, features, and functionality are owned by ListingIgnite and protected by applicable intellectual property laws</li>
              <li>You retain ownership of the listing data you submit and the marketing content generated from it</li>
            </ul>
          </Section>

          <Section title="8. Privacy">
            <p>Your use of ListingIgnite is also governed by our{' '}
              <Link to="/privacy" style={s.link} target="_blank" rel="noopener noreferrer">Privacy Policy</Link>,
              which is incorporated into these Terms by reference.
            </p>
          </Section>

          <Section title="9. Disclaimers">
            <ul style={s.list}>
              <li>ListingIgnite is provided "as is" without warranties of any kind</li>
              <li>We do not guarantee uninterrupted or error-free service</li>
              <li>We are not responsible for any decisions made based on AI-generated content</li>
              <li>We are not a licensed real estate brokerage and do not provide real estate advice</li>
            </ul>
          </Section>

          <Section title="10. Limitation of Liability">
            <p>To the maximum extent permitted by law, ListingIgnite shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service. Our total liability shall not exceed the amount you paid us in the 30 days prior to the claim.</p>
          </Section>

          <Section title="11. Termination">
            <p>We reserve the right to suspend or terminate accounts that violate these Terms of Service, with or without notice.</p>
          </Section>

          <Section title="12. Changes to Terms">
            <p>We may update these Terms from time to time. Continued use of the service after changes constitutes acceptance of the new Terms.</p>
          </Section>

          <Section title="13. Governing Law">
            <p>These Terms are governed by the laws of the United States. Any disputes shall be resolved in the appropriate courts.</p>
          </Section>

          <Section title="14. Contact" last>
            <p>For questions about these Terms, contact us at <a href="mailto:jason@listingignite.com" style={s.link}>jason@listingignite.com</a>.</p>
          </Section>

        </div>
      </div>
    </div>
  )
}

function Section({ title, children, last }: { title: string; children: React.ReactNode; last?: boolean }) {
  return (
    <section style={last ? { ...s.section, borderBottom: 'none', marginBottom: 0, paddingBottom: 0 } : s.section}>
      <h2 style={s.sectionTitle}>{title}</h2>
      <div style={s.sectionBody}>{children}</div>
    </section>
  )
}

const s: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #0f0f14 0%, #1a1025 100%)',
    padding: '48px 24px 80px',
    fontFamily: 'system-ui, "Segoe UI", Roboto, sans-serif',
  },
  container: {
    maxWidth: '760px',
    margin: '0 auto',
  },
  backLink: {
    display: 'inline-block',
    color: '#a855f7',
    fontSize: '14px',
    fontWeight: '500',
    textDecoration: 'none',
    marginBottom: '36px',
  },
  header: {
    marginBottom: '48px',
    paddingBottom: '36px',
    borderBottom: '1px solid #2e2e3a',
  },
  sparkle: {
    fontSize: '28px',
    color: '#a855f7',
    marginBottom: '16px',
  },
  pageTitle: {
    fontSize: '36px',
    fontWeight: '700',
    color: '#f3f4f6',
    margin: '0 0 8px',
    letterSpacing: '-0.5px',
  },
  lastUpdated: {
    fontSize: '13px',
    color: '#6b7280',
    margin: '0 0 16px',
  },
  disclaimer: {
    fontSize: '13px',
    color: '#6b7280',
    background: 'rgba(168, 85, 247, 0.06)',
    border: '1px solid rgba(168, 85, 247, 0.15)',
    borderRadius: '8px',
    padding: '12px 16px',
    margin: 0,
    lineHeight: '1.6',
    fontStyle: 'italic',
  },
  body: {},
  section: {
    marginBottom: '36px',
    paddingBottom: '36px',
    borderBottom: '1px solid #1e1e28',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#e5e7eb',
    margin: '0 0 12px',
    letterSpacing: '-0.2px',
  },
  sectionBody: {
    fontSize: '15px',
    color: '#9ca3af',
    lineHeight: '1.7',
  },
  list: {
    margin: '0',
    paddingLeft: '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  link: {
    color: '#a855f7',
    textDecoration: 'none',
  },
}
